PREFIX base:     <http://secti.pe.gov.br/indicador_cti/vocabulary/base#>
PREFIX canvas:   <http://secti.pe.gov.br/indicador_cti/vocabulary/canvas#>
PREFIX plano:    <http://secti.pe.gov.br/indicador_cti/vocabulary/planoAvaliacao#>
PREFIX met:      <http://secti.pe.gov.br/indicador_cti/vocabulary/metricas#>
PREFIX programa: <http://secti.pe.gov.br/indicador_cti/vocabulary/programa#>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?nomeMetrica ?finalidade ?va ?vm ?status
WHERE {
  # Busca somente o PBPG pelo ID
  ?progInstance base:id "PR1" . 
  ?progInstance programa:buscaAtingirEspecifico ?objetivo .

  # Busca o objetivo -> resultado -> questão -> métrica
  ?objetivo canvas:buscaAtingir ?resultado .
  ?questao  plano:alinhaComResultado ?resultado ;
            plano:temMetrica ?metrica .

  # Busca o valor atual e valor da meta
  ?metrica met:valorAtual ?va ;
           met:valorMeta  ?vm .
  
  OPTIONAL { ?metrica met:finalidade ?finalidade }
  OPTIONAL { ?metrica base:nome ?nomeMetrica }

  # Lógica da finalizade(status foi inserido para uma melhor visualização)
  BIND(
    IF(
      (?finalidade = "Maximizar" && xsd:decimal(?va) >= xsd:decimal(?vm)) ||
      (?finalidade = "Minimizar" && xsd:decimal(?va) <= xsd:decimal(?vm)) ||
      (?finalidade = "Equilibrar" && abs(xsd:decimal(?va) - xsd:decimal(?vm)) <= 0.05) || # margem de tolerância definida arbitrariamente para verificar se os valores estão em situação de equilíbrio
      (!BOUND(?finalidade) && xsd:decimal(?va) >= xsd:decimal(?vm)),
      "META ATINGIDA", 
      "NAO ATINGIDA"
    ) AS ?status
  )
}
ORDER BY ?nomeMetrica
